spring: 
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
    application:
      name: microservicecloud-config-chaoyang-dev

---
spring:
  profiles: test
    application:
      name: microservicecloud-config-chaoyang-test 